version: '3'

services:
  db-app:
    build: .
    networks:
      - proxy
    environment:
       VIRTUAL_HOST: db.ztf.snad.space
       HTTPS_METHOD: noredirect
       DYNDNS_HOST: db.ztf.snad.space
       LETSENCRYPT_HOST: db.ztf.snad.space
       LETSENCRYPT_EMAIL: db.ztf.snad.space@homb.it
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    restart: always

networks:
  proxy:
    external:
      name: proxy
